CC = gcc
CFLAGS = -std=c99 -Wall -pedantic

all: ttt1.o ttt2.o alphatoe show_node count_nodes

ttt1.o: ttt1.c ttt.h
	$(CC) $(CFLAGS) -c ttt1.c

ttt2.o: ttt2.c ttt.h ttt1.o
	$(CC) $(CFLAGS) -c ttt2.c

alphatoe.o: alphatoe.c
	$(CC) $(CFLAGS) -c alphatoe.c

alphatoe: alphatoe.o ttt1.o ttt2.o
	$(CC) $(CFLAGS) -o alphatoe ttt1.o ttt2.o alphatoe.o

show_node.o: show_node.c
	$(CC) $(CFLAGS) -c show_node.c

show_node: show_node.o ttt1.o ttt2.o
	$(CC) $(CFLAGS) -o show_node ttt1.o ttt2.o show_node.o

count_nodes.o: count_nodes.c
	$(CC) $(CFLAGS) -c count_nodes.c

count_nodes: count_nodes.o ttt1.o ttt2.o
	$(CC) $(CFLAGS) -o count_nodes ttt1.o ttt2.o count_nodes.o

clean:
	rm -i *.o alphatoe show_node count_nodes
